name = "HamiltonFilters"
uuid = "0b36f51d-d584-4441-8150-7f453e52fbad"
authors = ["Enrico Wegner"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
DataFrames = "1.7.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
